rootProject.name = "LoMu-QQBot"
include("common")
include("http-client")
include("ai")
include("core")
include("nutdraw")
include("qgbot")
include("onebot")
include("plugins:character")
include("plugins:player")
include("plugins:tier")
include("plugins:news")
include("plugins:query-statistics")
