[versions]
kotlin = "2.3.21"
simbot-core = "4.14.0"
simbot-qq = "4.5.0"
simbot-onebot = "1.9.0"
ktor = "2.3.12"
koin = "3.5.5"
coroutines = "1.8.1"
kotlin-logging = "6.0.3"
caffeine = "3.2.3"
logback = "1.4.11"
reflections = "0.10.2"
mongodb = "5.3.1"
ktorm = "3.6.0"
postgresql = "42.7.3"
sqlite-jdbc = "3.53.1.0"
hikari = "5.1.0"
tinypinyin = "2.0.1"
koog = "1.0.0"
jsoup= "1.18.1"
kotlinx-serialization = "1.10.0"
skiko = "0.150.1"

[libraries]
tinypinyin = { module = "com.github.promeg:tinypinyin", version.ref = "tinypinyin" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
simbot-core = { module = "love.forte.simbot:simbot-core", version.ref = "simbot-core" }
simbot-component-qq = { module = "love.forte.simbot.component:simbot-component-qq-guild-core", version.ref = "simbot-qq" }
simbot-component-onebot = { module = "love.forte.simbot.component:simbot-component-onebot-v11-core", version.ref = "simbot-onebot" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-freemarker = { module = "io.ktor:ktor-server-freemarker", version.ref = "ktor" }
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
jsoup-parse = {module="org.jsoup:jsoup",version.ref="jsoup"}
ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-support-postgresql = { module = "org.ktorm:ktorm-support-postgresql", version.ref = "ktorm" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
skiko-awt = { module = "org.jetbrains.skiko:skiko-awt", version.ref = "skiko" }
skiko-runtime-windows-x64 = { module = "org.jetbrains.skiko:skiko-awt-runtime-windows-x64", version.ref = "skiko" }
skiko-runtime-linux-x64 = { module = "org.jetbrains.skiko:skiko-awt-runtime-linux-x64", version.ref = "skiko" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
